### ISSUE TITLE
Initial width/height does not take style sheet into account

### ISSUE THREAD

**Issue by bert-github** [w3c/i-slide#42]
For an example, see https://w3c.github.io/scribe2/sample-slides.html

The slide inside the \<i-slide> element is drawn with a width of 300px (the default size) and doesn't take the size of the \<i-slide> element into account.

Maybe it is a timing issue: Maybe the slide is drawn before all style sheets are loaded and thus before the \<i-slide> element has its correct size. Indeed, when the link to the style sheet is replaced by an inline style sheet, the size is correctly applied.

There is a ResizeObserver that resizes the slide when the \<i-slide> element is resized. When you make the window narrower and then wider again, or when you change the style of the \<i-slide> in some way, that observer indeed redraws the slide to the size of the \<i-slide> element. But the observer seems to miss the first application of the style sheet.

**Comment by bert-github** [comment]
When I change the following in ISlide.js, it seems to work. But I don't know if this is also correct in other situations.

Line 502:
    -    const width = this.#width;
    +    const width = this.clientWidth || this.#width;
 
Line 507:
    -    let height = this.#height ||
    +    let height = this.clientHeight || this.#height ||

Line 758:
    -    const targetWidth = this.#width;
    +    const targetWidth = this.clientWidth || this.#width;

**Comment by tidoust** [comment]
Yes, thanks for looking into it, @bert-github! That looks like the right fix to me.

The race condition occurs when the ResizeObserver gets called too soon, i.e. when the code has not yet done a first render pass. In such cases, the resize event gets ignored because the theory is that the render pass will actually use the correct values... except it doesn't since it forgets to take `clientWidth` and `clientHeight` into account.

I haven't managed to reproduce this situation locally yet with an atomic test, perhaps because fetching the slides goes too fast in tests, or because this requires a combination of CSS properties that I haven't quite figured out yet (but which one?). I'll dig some more as it would be good to add some non-regression test.

This also made me wonder whether `ISlide.width` should reflect the content attribute or the width of the visual content. It seems both are possible on the Web platform for replaced elements: the `width` IDL attribute for `iframe` reflects the content attribute, whereas it reflects the actual width of the image for `img`. I don't know the rationale. I propose to stick to reflecting the content attribute for simplicity.

**Comment by tidoust** [comment]
> I haven't managed to reproduce this situation locally yet with an atomic test, perhaps because fetching the slides goes too fast in tests, or because this requires a combination of CSS properties that I haven't quite figured out yet (but which one?).

Ah, reproducing is actually easy, one just has to set a `height` CSS property on the `<i-slide>` element. I initially failed because I was setting `width`. This can likely be explained by the way content gets laid out in CSS. Anyway, I'll add a non-regression test accordingly and fix the code.
